### ISSUE TITLE
polish translation

### ISSUE THREAD

**Issue by ZainSugieres** [Jeremiidesu/osu-rank#12]
Language you're translating to: Polish
Your username: Zain Sugieres

---- Translate under this line ----

Your API key is incorrect.= Twój klucz API jest niepoprawny.
You didn't enter a key!= Nie wprowadziłeś klucza!

API key= Klucz API
Enter your osu! API key= Wprowadź swój klucz API osu!
No key? Get one here!= Nie masz klucza? Zdobądź jeden tutaj!
You need an API key if you want to use the program.= Potrzebujesz klucza API żeby korzystać z programu.
osu!rank will now close.= osu!rank wyłączy się

Test key= Klucz testowy

About osu!rank= O osu!rank

**Comment by HoutarouOreki** [comment]
[StringList 4.4.txt](https://github.com/otaku-overclocks/osu-rank/files/777815/StringList.4.4.txt)
[StringList 4.5.txt](https://github.com/otaku-overclocks/osu-rank/files/777816/StringList.4.5.txt)

Can I get previous string lists? I want to make some little adjustments.

**Comment by Erinaaaaaaa** [comment]
I think it would have been better to open a new issue with the new translations. Nonetheless i'm gonna reopen this one. What do you mean by the "previous string lists" though? All the needed lists are in the folder. If you want the previous translated stringlists, then sorry: I don't store them.

**Comment by breadbyte** [comment]
@HoutarouOreki 
https://github.com/otaku-overclocks/osu-rank/tree/master/osu-rank/osu-rank/Stringlists
and create a new issue with the translation tweaks.

Alternatively,
Download [TxEditor](https://unclassified.software/en/source/txtranslation) and fork the repo, update [the txd file ](https://github.com/otaku-overclocks/osu-rank/tree/master/osu-rank/osu-rank/Translation)and make a pull request, or make an issue referencing the pull request.
