### ISSUE TITLE
Text cut off in API key request text box

### ISSUE THREAD

**Issue by ghost** [Jeremiidesu/osu-rank#21]
Basically the text gets cut off at the bottom.
![pic](https://puu.sh/rGSfg/6a01fa60b5.png)

Had to blur out the API key, sorry. :disappointed:

**Comment by Erinaaaaaaa** [comment]
No problem about blurring the API key, it's common sense. I'll look into that

**Comment by Erinaaaaaaa** [comment]
Um, sorry but this is how it's supposed to look according to the code

**Comment by Erinaaaaaaa** [comment]
The left label "Enter your osu! API key" is supposed to be "Inserisci la tua chiave API di osu!" and the right label "No key? Get one here!" is supposed to be "Non hai una chiave? Puoi prenderne una qui!", so I don't see where's the problem

**Comment by Erinaaaaaaa** [comment]
![](https://cdn.discordapp.com/attachments/220981942454190080/237993867020861441/osu-rank_2016-10-18_19-42-03.png)

New stuffs to the rescue! not the labels, but the textbox content shouldn't be cut off!
