### ISSUE TITLE
Italian translation issue

### ISSUE THREAD

**Issue by ghost** [Jeremiidesu/osu-rank#22]
There is this section:
![pic](https://puu.sh/rGSIj/0305c839a8.png)

the word "posizioni" would be more appropriate rather than "ranks".

You can find the fixed 3.0 translation file [here](https://puu.sh/rGSPU/5d1de09572.txt).

**Comment by Erinaaaaaaa** [comment]
um, and what about "1 rank"? you didn't seem to edit this one

**Comment by ghost** [comment]
If the context is the same of the {#} ranks then you can change it to {#} posizione
