### ISSUE TITLE
osu! API key still asked and sent to ripple servers even though ripple doesn't need any

### ISSUE THREAD

**Issue by Erinaaaaaaa** [Jeremiidesu/osu-rank#32]

**Comment by Erinaaaaaaa** [comment]
Half fixed. Ability to use osu!rank without key for ripple functionality, though key is still sent.

**Comment by breadbyte** [comment]
Try sending in a random jumble of letters or something instead, and
probably disable the ripple option when you have entered an api key in the
box that first appears. 
http://ripple.moe/api/get_user?type=string&u=breadman&m=0&k=uwu works, so it is a very easy fix. I'll
do it when i get home. I don't have google auth right now sadly so i can't
modify :(

**Comment by Erinaaaaaaa** [comment]
@Mark9870 i'll just edit the ripple.GetUser() and ripple.GetUserAsync() so that they don't need any apiKey parameter nor use any
