### ISSUE TITLE
Russian Translation 3.1 and 4.0 update by Killerbyte

### ISSUE THREAD

**Issue by Killer0byte** [Jeremiidesu/osu-rank#4]
Language you're translating to: Russian
Your username: Killerbyte

---- Translate under this line ----

Save= Сохранить
Saved= Сохранено

**Comment by Killer0byte** [comment]
Language you're translating to: Russian
Your username: Killerbyte

---- Translate under this line ----

Your API key is incorrect.= Ваш ключ API не неправильный.
You didn't enter a key!= Вы не ввели ключ!

API key= Ключ API
Enter your osu! API key= Напишите ваш ключ osu! API
No key? Get one here!= Нет ключа? Возьмите один сдесь!
You need an API key if you want to use the program.= Вам нужен ключ API если вы хотите использовать программу.
osu!rank will now close.= osu!rank сейчас закроется.

Test key= Тест ключ

About osu!rank= Об osu!rank

**Comment by breadbyte** [comment]
Added on commit 47f73b1.
